apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
  - image: busybox
    name: busybox
    resources:
      limits:
        cpu: "0.2"
        memory: "1Gi"
